### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by HelgeStenstrom**
Dependency for MacOS, to make test class TestJave2, void testJaveInits() pass on Mac.

### CODE REVIEW

**Comment by goxr3plus** [comment]
This can be done by automatically detecting os somehow and based on OS download exe for windows or Mac os, downloading both for every os is not the best option.


I think we will pass from Maven to Gradle. :)

**Comment by HelgeStenstrom** [comment]
Profiles can probably solve this. http://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by goxr3plus** [comment]
Can you make in this pull requests so that happens? In windows that dependency is loaded and on Mac the other dependency is loaded :)?

**Comment by HelgeStenstrom** [comment]
Two hours ago, I didn't know anything about Maven profiles. I still don't know enough to solve this.
A strange thing: I removed the lines in the pom.xml, that I added for Mac, and it still works. It seems that maven has imported the needed file on my machine, and will not forget it, unless I force it, which I don't know how to do. 

Another thing that complicates this: Compile host OS and architecture is not necessarily the same as target OS and architecture. Or is it? You know best.

**Comment by HelgeStenstrom** [comment]
Does it make sense to have
	requires jave.nativebin.win64;
in module-info.java, when running or compiling on a Mac?

**Comment by HelgeStenstrom** [comment]
This is not intended for merging as-is, it's just for discussion.
If it works the way I think, jave dependencies for mac will only be used on a Mac build host.
I also found out that jave.nativebin is not needed in module-info.java. I think this file should be kept as short as possible, with no requires that are not needed. 
But if you want 
	requires jave.nativebin.win64;
	requires jave.nativebin.osx64;
then the corresponding dependency must be correct in the pom.xml. It works on my machine, but that is no guarantee that it's made in the right way. 

With the help of test file IsPlatformSupported.java, you can find out the strings that are used by Maven to identify the platform. I could of course not do it for Windows.

**Comment by goxr3plus** [comment]
Yes y9u are right for the module i just putted 'jave.nativebin.win64' for testing there becausei cannot get it work.

That library exports a native binary to a folder but it doesn't work correctly with java 11 it says it doesn't find resources.

**Comment by goxr3plus** [comment]
Can you make this small test for me? Start the application put a song to a player and tell me if the spectrum analyser above the dj mode disc is drawn or it is always lagging forever throwing errors inside the application?

**Comment by HelgeStenstrom** [comment]
Now I have actually run the application for the first time, and got some sound.

https://www.dropbox.com/s/xotwdzya1vcuyqz/Sk%C3%A4rmklipp%202019-07-08%2014.41.30.png?dl=0 (when music is running)

https://www.dropbox.com/s/yciecxjal8j7wqh/Sk%C3%A4rmklipp%202019-07-08%2014.41.42.png?dl=0 (when paused)

I think there is the thing you call "spectrum analyzer", although it doesn't look like a spectrum analyzer to me. The graph of a spectrum analyzer has a frequency axis; this one seems to have a time axis.

But I guess the test is to your satisfaction?

**Comment by goxr3plus** [comment]
Yes yes you are right it has a time access :)
 Very strange it works for you hm.... It doesn't work on windows for me.

Ouhhhhhhhhh

**Comment by goxr3plus** [comment]
Thank you so much for testing.

I am suspicious about something other too.

If the bin is already extracted in Mac os from previous XR3PLAYER version.

You can delete it to test, i will tell you how to find the path of it.

**Comment by HelgeStenstrom** [comment]
Which bin are you talking about?

**Comment by goxr3plus** [comment]
JAVE2 library is using FFMpeg executable actually it id a wrapper, so it actually exports the. Exe for example for Windows on a folder, from there through its api i call the functionality that i want.


So in MAC it exports somewhere an executable file.

How you can find out where.

Inside Jave2 library there is a class called DefaultLocator or something like that, inside there it has the copy method so you can start XR3Player with a debugger and put a breakpoint inside that class.

**Comment by goxr3plus** [comment]
I added the changes of this pull request by hand , on the latest commit :) So i am closing.

One more think , i don't like that much Maven profiles so i think we will be passing on Gradle which makes it way more easier .

**Pull request closed without merging**
