### PR TITLE
Rewrite Libraries as Maven Dependencies

### PR DESCRIPTION
**Pull request by Valkryst**
Eliminates the need for (most) Jar files by adding Maven to the project.

You'll want to test this out before merging. I've updated a few of the libraries while writing the POM file.

### CODE REVIEW

**Comment by goxr3plus** [comment]
WOW thank you so much for making this effort.

I will accept your pull request but we have some problems . Some plugins , for example **javasysmon** has a serious bug which makes it not working for Windows 7 . I have fixed it mixing two different jar files and creating a new **javasysmon** which you can see inside the libraries folder . I will create a repository for that one just to upload the file and get it using **JitPack.io** . 

Apart from that , i  have just converted the XR3Player Eclipse Project to Maven project and i have very strange errors when i am exporting it as .jar with the external libraries ( like before i make it Maven Project ) , i get very strange errors , like something is missing from libraries . 

I am working on it .

Thank you so so much for your effort :)

**Comment by goxr3plus** [comment]
I have completely fixed the pom.xml based on yours , but i have problems when exporting the jar file doesn't works .... i get very strange errors . The pom is below : 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.github.goxr3plus</groupId>
	<artifactId>XR3Player</artifactId>
	<version>3.0.0</version>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<build>
		<sourceDirectory>src</sourceDirectory>
		<resources>
			<resource>
				<directory>resources</directory>
			</resource>
		</resources>
		<testSourceDirectory>testing</testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.0.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.10.4</version>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

	<!-- Dependencies -->

	<dependencies>
		<!-- JAVAFX GRAPHICS LIBRARIES -->
		<dependency>
			<groupId>org.controlsfx</groupId>
			<artifactId>controlsfx</artifactId>
			<version>8.40.14</version>
		</dependency>
		<dependency>
			<groupId>com.jfoenix</groupId>
			<artifactId>jfoenix</artifactId>
			<version>1.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.fxmisc.richtext</groupId>
			<artifactId>richtextfx</artifactId>
			<version>0.7-M5</version>
		</dependency>
		<!-- JAVA NATIVE CODE FOR CONTROLLING HARDWARE -->
		<dependency>
			<groupId>com.github.goxr3plus</groupId>
			<artifactId>javasysmon</artifactId>
			<version>V3.5.0</version>
		</dependency>
		<dependency>
			<groupId>com.1stleg</groupId>
			<artifactId>jnativehook</artifactId>
			<version>2.1.0</version>
		</dependency>
		<!-- DATABASE DRIVERS -->
		<dependency>
			<groupId>org.xerial</groupId>
			<artifactId>sqlite-jdbc</artifactId>
			<version>3.20.1</version>
			<scope>test</scope>
		</dependency>
		<!-- ETC LIBRARIES -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.6</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId> <!-- Exclude Project-E from Project-B -->
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.fxmisc.easybind</groupId>
			<artifactId>easybind</artifactId>
			<version>1.0.3</version>
		</dependency>
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.10.3</version>
		</dependency>
		<dependency>
			<groupId>com.github.cliftonlabs</groupId>
			<artifactId>json-simple</artifactId>
			<version>2.3.0</version>
		</dependency>
		<!-- JAVA-GOOGLE-SPEECH-API -->
		<dependency>
			<groupId>com.github.goxr3plus</groupId>
			<artifactId>java-google-speech-api</artifactId>
			<version>V2.1</version>
		</dependency>
		<!-- AUDIO TAG READERS -->
		<dependency>
			<groupId>com.mpatric</groupId>
			<artifactId>mp3agic</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.bitbucket.ijabz</groupId>
			<artifactId>jaudiotagger</artifactId>
			<version>v2.2.5</version>
		</dependency>
		<!-- AUDIO SUPPORT -->
		<dependency>
			<groupId>com.googlecode.soundlibs</groupId>
			<artifactId>mp3spi</artifactId>
			<version>1.9.5.4</version>
		</dependency>
		<dependency>
			<groupId>org.jflac</groupId>
			<artifactId>jflac-codec</artifactId>
			<version>1.5.2</version>
		</dependency>
		<dependency>
			<groupId>com.github.Trilarion</groupId>
			<artifactId>java-vorbis-support</artifactId>
			<version>v1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.soundlibs</groupId>
			<artifactId>tritonus-share</artifactId>
			<version>0.3.7.4</version>
		</dependency>
		<!-- AUDIO EXPERIMENTAL TESTS -->
		<!-- <dependency> <groupId>com.googlecode.soundlibs</groupId> <artifactId>tritonus-all</artifactId> 
			<version>0.3.7.2</version> </dependency> -->
	</dependencies>

</project>
```

**Comment by goxr3plus** [comment]
When i export the project as XR3Player.jar and try to run it from cmd with ```java -jar XR3Player.jar``` i get : 

```
Exception in thread "main" Exception in thread "JavaFX Application Thread" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:383)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        ... 5 more
java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplicationWithArgs$156(LauncherImpl.java:352)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Location is not set.
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at application.windows.WelcomeScreen.<init>(WelcomeScreen.java:55)
        at application.Main.<clinit>(Main.java:119)
        ... 11 more
```

Running it from inside Eclipse works but not recognizing the sqlite driver ..... da fuuuuuck 

```
java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:\Users\GOXR3PL
US\Desktop\GitHub\XR3Player\target\classes\XR3DataBase\4756\dbFile.db
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at application.database.DbManager.initialize(DbManager.java:144)
	at application.Main.lambda$9(Main.java:512)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by Valkryst** [comment]
I'll try to take a look at your updated POM file over the weekend.

I believe, in the exception you posted, the issue is near the bottom where it says "Caused by: java.lang.IllegalStateException: Location is not set.". It happens on line 55 of the WelcomeScreen file. The higher parts of the exception are probably) caused by that, but I'm not 100% sure.

**Comment by goxr3plus** [comment]
I pushed one more big commit today . *I want to make it export XR3Player.jar and the depencities to another folder named XR3Player_lib* . Hopefully i will find the way :)

**Comment by goxr3plus** [comment]
I managed to use Maven for exporting the Project as XR3Player.jar and all the depencities to a separate folder named XR3Player_lib . Though other problems occur trying to run it .

The below errors occur sff ..

``` cmd
C:\Users\GOXR3PLUS\Desktop>java -jar XR3Player.jar
Outside of Application Start Method
Stream player Status -> NOT_SPECIFIED
Oct 23, 2017 7:58:10 PM xplayer.visualizer.fxpresenter.VisualizerWindowController <init>
SEVERE: VisualizerWindowController FXML can't be loaded!
javafx.fxml.LoadException:
file:/C:/Users/GOXR3PLUS/Desktop/XR3Player.jar!/fxml/VisualizerWindowController.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at xplayer.visualizer.fxpresenter.VisualizerWindowController.<init>(VisualizerWindowController.java:141)
        at xplayer.presenter.XPlayerController.initialize(XPlayerController.java:425)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at xplayer.presenter.XPlayerController.<init>(XPlayerController.java:368)
        at applicationmodes.librarymode.LibraryMode.initialize(LibraryMode.java:325)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at applicationmodes.librarymode.LibraryMode.<init>(LibraryMode.java:252)
        at application.Main.<clinit>(Main.java:231)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplicationWithArgs$156(LauncherImpl.java:352)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
        ... 43 more
Caused by: java.lang.IllegalStateException: Location is not set.
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at application.borderless.BorderlessScene.<init>(BorderlessScene.java:66)
        at xplayer.visualizer.fxpresenter.VisualizerWindowController.initialize(VisualizerWindowController.java:157)
        ... 53 more
```

**Comment by GregoryHlavac** [comment]
@goxr3plus Ever considered switching to gradle for a bit more robust of a build, and overall easier to read?

**Comment by goxr3plus** [comment]
@Valkryst All ready i have fixed all the errors . The pom.xml is updated and working :) . Thank you so much for the motivation and help on this .

Actually the error to the final jar file occured because i was compiling with Java 9 , when the XR3Player has not yet passed to Java 9 . So now it works perfectly with java 1.8.0_141 .

Next step is maybe converting it to Gradle project .

**Comment by goxr3plus** [comment]
@GregoryHlavac Hello my friend :) I just have successfuly converted XR3Player to a Maven Project . I am very new to Gradle ... Can you help me based on the current working pom.xml to convert it into a Gradle Project ? :)

**Comment by GregoryHlavac** [comment]
Perhaps, but I suggested it due to your increased degree of complexity in the build that I was reading up on in this discussion with the custom library stuff and such; you could plausibly have it download an existing maven artifact for the library you use then patch in your updated classfile as needed.

**Comment by goxr3plus** [comment]
@GregoryHlavac  If you can help me doing this i would be very grateful . Current pom.xml works excellent . Not so complex really . It just has two plugins for exporting the depencities of the project to a different folder and one plugin for creating the XR3Player.jar file . Apart from that we can see all the depencities on the end of pom file . Really easy to read .

I have been told that Gradle is superior to Maven , Ant , Ivy etc . If you can make a prototype gradle.build like @Valkryst  did for me , i may change it to Gradle :) .

**Comment by goxr3plus** [comment]
@Valkryst  Hello my friend  . This repository has completely being converted into Maven project :) . Only 1 problem . I can't find some depencities anywhere . For example JAudioTager 2.2.6  . Some others i uploaded on my repositories on Github and i am using JitPack to take them . 

Apart from that all excellent .

**Comment by goxr3plus** [comment]
@Valkryst  I think all are working as expected with Maven :) . I will close this pull request .

Thank you so much :)

**Comment by GregoryHlavac** [comment]
@goxr3plus Doesn't look like jaudiotager 2.2.6 exists? Only goes up to 2.2.5 on the bintray maven repo that supplies that artifact?

**Comment by goxr3plus** [comment]
@GregoryHlavac  I found a solution making a github repository ( https://github.com/goxr3plus/jaudiotagger ) and taking it from there lol :)

You can see a discussion here with the owner of the project , i will keep this solution until that boss releases 2.2.7 or do it correctly for 2.2.6 :)  

https://bitbucket.org/ijabz/jaudiotagger/issues/231/made-github-repository-for-jaudiotagger

**Pull request closed without merging**
