### PR TITLE
Replace indexed for loop with foreach

### PR DESCRIPTION
**Pull request by HelgeStenstrom**
Based on code inspection, this is a feature for Java > Java 5.
The changes were automated in IntelliJ: Analyze --> Inspect code. In the inspection results, I found Java language level migration aids -> Java 5. 
A also renamed one or two variables, because I didn't think the automatically created name was the best.

### CODE REVIEW

**Comment by goxr3plus** [comment]
Oouuu i see, i need to think more about this in terms of speed .

If i am not wrong Indexed loops are faster than foreach, here we are modifying loops that are running thousands of times per second when visualizer is drawing which might have a performance issue.

Let me know where i am wrong.

**Comment by goxr3plus** [comment]
After a small google search https://www.google.gr/search?q=java+indexed+for+loop+vs+for+each+loop.comspeed+comparison&oq=java+indexed+for+loop+vs+for+each+loop.comspeed+comparison+&aqs=chrome..69i57.13795j0j9&sourceid=chrome-mobile&ie=UTF-8 i would like your final opinion.

I have to admit the code readability has improved a lot.

**Comment by HelgeStenstrom** [comment]
I didn't think about performance when I did the change. But recommendations I have read in various books tell me to not optimize prematurely. From Effective Java, 3rd edition, by Joshua Bloch:

Item 67: Optimize judiciously
There are three aphorisms concerning optimization that everyone should know:
More computing sins are committed in the name of efficiency (without necessarily
achieving it) than for any other single reason—including blind stupidity.
—William A. Wulf [Wulf72]
We should forget about small efficiencies, say about 97% of the time: premature
optimization is the root of all evil.
—Donald E. Knuth [Knuth74]
We follow two rules in the matter of optimization:
Rule 1. Don’t do it.
Rule 2 (for experts only). Don’t do it yet—that is, not until you have a
perfectly clear and unoptimized solution.
—M. A. Jackson [Jackson75]
All of these aphorisms predate the Java programming language by two
decades. They tell a deep truth about optimization: it is easy to do more harm than
good, especially if you optimize prematurely. In the process, you may produce
software that is neither fast nor correct and cannot easily be fixed.
Don’t sacrifice sound architectural principles for performance. Strive to write
good programs rather than fast ones. If a good program is not fast enough, its
architecture will allow it to be optimized. Good programs embody the principle of
information hiding: where possible, they localize design decisions within individual
components, so individual decisions can be changed without affecting the
remainder of the system (Item 15).

**Comment by HelgeStenstrom** [comment]
I would assume that the compiler would optimize the two ways of doing loops, so that they are the same. If it is important, it should be measured. I don't know how to do that.

**Pull request merged**
