### PR TITLE
Java7migration

### PR DESCRIPTION
**Pull request by HelgeStenstrom**
Replace explicit type with <>
This is an automated change, based on migration from Java7.

### CODE REVIEW

**Comment by goxr3plus** [comment]
PERFECT 👌 :) ♥ You are doing an excellent contribution

**Comment by goxr3plus** [comment]
Merge button is disabled i don't know why....

I was able to approve only 2 pull requests please press the merge if you can or let me know why i cannot merge

**Comment by goxr3plus** [comment]
When you merge start from the oldest pull request to the newest so you don't have conflicts.

Please verify :)

**Comment by HelgeStenstrom** [comment]
I partly understand the conflicts, but I didn't expect them. They are from another of my pull requests (the JavaDoc change set). I will look into it. I probably have to rebase, now that the master has changed.

**Comment by goxr3plus** [comment]
Hm this one has conflicts with 3 classes . My fault probably because i merged a later commit before merging this .

**Comment by HelgeStenstrom** [comment]
My changes and pull requests were meant to be independent of each other. I
think I can fix this within 24 hours.

mån 24 juni 2019 kl. 10:14 skrev GOXR3PLUS STUDIO <notifications@github.com

**Comment by goxr3plus** [comment]
This seems good i am merging , read the code today :)

**Comment by goxr3plus** [comment]
Don't worry i will resolve them now , let me do it :)

**Comment by goxr3plus** [comment]
Done :)

**Pull request merged**
