### PR TITLE
More tests to demonstrate a probable regex bug.

### PR DESCRIPTION
**Pull request by HelgeStenstrom**
Rename the test class accordingly.

Please check if the bug is real or not. I might have misunderstood the intention of the matching strings.

But if the tests look OK, then vertical bars should be removed from line 160-162 of ConsoleWindowController, in a separate commit.

### CODE REVIEW

**Comment by HelgeStenstrom** [comment]
I configure tests like this to run all defined tests:
https://www.dropbox.com/s/fi3e5byisx3n0gb/Sk%C3%A4rmklipp%202019-06-26%2023.28.02.png?dl=0

**Comment by goxr3plus** [comment]
I am a little bit lost on the purpose of this i have to admit.

**Comment by goxr3plus** [comment]
Let me know in simple words what we really trying to solve or test out.

A regex is not working correctly somewhere?

**Comment by HelgeStenstrom** [comment]
Look in ConsoleWindowController and tell me the purpose of 

pattern1.matcher(command).matches()

in the context of (close to line 191):

```java
		if (command.startsWith("player")) {
			System.out.println(command);
			final String[] array = command.split(":");

			// It must be 3 [format = "player"+"key"+"action"]
			if (array.length == 3 && pattern1.matcher(command).matches()) {
```

I think the purpose of pattern1.matcher(command).matches() is to return true if the command has the right form. 

"player:+22:anyWords"

is the right form.

"player:|22:anyWords"

is not the form I think you intended the command to have.

Am I right?

**Comment by HelgeStenstrom** [comment]
What happens in

Integer.parseInt(array[1]));

When the command contains a vertical bar?

I think parseInt accepts 123, +123, -123 but not x123 or |123.

But I haven’t tried.

**Comment by goxr3plus** [comment]
Ooou now i catch you.

**Pull request merged**
